### ISSUE TITLE
Add new Category (Twitter accounts to follow)

### ISSUE THREAD

**Issue by chefk5** [chefk5/react-native-start-guide#5]
Create a new category named "Twitter accounts to follow" and add all Twitter accounts that talks bout react native.
ex: https://twitter.com/FernandoTheRojo

**Comment by Nikhil-1503** [comment]
Hey, can I work on this?

**Comment by chefk5** [comment]
Yes, assigned. Good luck!

**Comment by chefk5** [comment]
Nice work @Nikhil-1503 . Will merge
